### ISSUE TITLE
環境構築する

### ISSUE THREAD

**Issue by kijimad** [kijimaD/novelify#6]
dockerをインストールしてから
docker-compose build
docker-compose up -d

**Comment by kijimad** [comment]
<a href="https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-20-04-ja">Ubuntu 20.04へのDockerのインストールおよび使用方法 | DigitalOcean</a>
を参考に.

同じ場所でエラーに出るところまで。

**Comment by kijimad** [comment]
![image](https://user-images.githubusercontent.com/11595790/105865481-54138d00-6036-11eb-966c-e5fe320de21b.png)

**Comment by kijimad** [comment]
![image](https://user-images.githubusercontent.com/11595790/105980786-a2796800-60d8-11eb-99ce-9edd5871ebe6.png)

とりあえずポートを書き換えた
```
version: '3'
services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5400:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/novelify
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:

```
